const FLAG_SIMULATION_NEGATIVE_BINOMIAL_VARY_RANK_SMALL                 = false
const FLAG_SIMULATION_NEGATIVE_BINOMIAL_VARY_RANK_MEDIUM                = true
const FLAG_SIMULATION_NEGATIVE_BINOMIAL_VARY_RANK_LARGE                 = false

const FLAG_SIMULATION_NEGATIVE_BINOMIAL_VARY_MISSING_PERCENTAGE_SMALL   = false
const FLAG_SIMULATION_NEGATIVE_BINOMIAL_VARY_MISSING_PERCENTAGE_MEDIUM  = false
const FLAG_SIMULATION_NEGATIVE_BINOMIAL_VARY_MISSING_PERCENTAGE_LARGE   = false




FLAG_SIMULATION_NEGATIVE_BINOMIAL_VARY_RANK_SMALL ?
  include("simulation_negbin_vary_rank_small.jl")  : nothing

FLAG_SIMULATION_NEGATIVE_BINOMIAL_VARY_RANK_MEDIUM ?
  include("simulation_negbin_vary_rank_medium.jl") : nothing

FLAG_SIMULATION_NEGATIVE_BINOMIAL_VARY_RANK_LARGE ?
  include("simulation_negbin_vary_rank_large.jl") : nothing
